var cryptoList = {list:[]};
cryptoList.list = [  [ 'AAVE', 'Aave' ],
  [ 'ALGO', 'Algorand' ],
  [ 'ATOM', 'Cosmos' ],
  [ 'BAL', 'EThe Balancer' ],
  [ 'BAND', 'Band Protocol' ],
  [ 'BAT', 'Basic Attention Token' ],
  [ 'BCH', 'Bitcoin Cash' ],
  [ 'BNT', 'Bancor Network Token' ],
  [ 'BSV', 'Bitcoin Satoshis Vision' ],
  [ 'BTC', 'Bitcoin' ],
  [ 'CGLD', 'Celo' ],
  [ 'COMP', 'Compound' ],
  [ 'CVC', 'Civic' ],
  [ 'DAI', 'Dai' ],
  [ 'DASH', 'Dash' ],
  [ 'DNT', 'districtOx' ],
  [ 'EOS', 'EOS' ],
  [ 'ETC', 'Ethereum Classic' ],
  [ 'ETH', 'Ethereum ' ],
  [ 'FIL', 'Filecoin' ],
  [ 'GRT', 'The Graph ' ],
  [ 'GNT', 'Golem' ],
  [ 'KNC', 'Kyber Network ' ],
  [ 'LINK', 'Chainlink ' ],
  [ 'LOOM', 'Loom Network ' ],
  [ 'LRC', 'Loopring' ],
  [ 'LTC', 'Litecoin' ],
  [ 'MANA', 'Decentraland ' ],
  [ 'MKR', 'Maker' ],
  [ 'NMR', 'Numeraire' ],
  [ 'NU', 'NuCypher' ],
  [ 'OMG', 'OMG Network' ],
  [ 'OXT', 'Orchid' ],
  [ 'REN', 'Ren' ],
  [ 'REP', 'Augur' ],
  [ 'SNX', 'Synthetix' ],
  [ 'USDC', 'USD Coin' ],
  [ 'UMA', 'Universal Market Access' ],
  [ 'UNI', 'Uniswap' ],
  [ 'WBTC', 'Wrapped Bitcoin' ],
  [ 'XLM', 'Stellar Lumens' ],
  [ 'XRP', 'Ripples' ],
  [ 'XTZ', 'Tezos' ],
  [ 'YFI', 'Yearn.finance' ],
  [ 'ZEC', 'Zcash' ],
  [ 'ZRX', '0x ' ]];

  module.exports = cryptoList;
